### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by a-crate** [regolith-linux/regolith-ftue#3]
I think you should consider adding a license file, for clarity. I know that debian/copyright states the license for all files but if I wasn't previously familiar with debian packaging I wouldn't know where to look for that. It would make things a little easier on packagers in other distributions.

**Comment by cfsmp3** [comment]
> I think you should consider adding a license file, for clarity. I know that debian/copyright states the license for all files but if I wasn't previously familiar with debian packaging I wouldn't know where to look for that. It would make things a little easier on packagers in other distributions.

Debian package linter explicitly complain if you add a LICENSE file to the package if such license is a generic one; see

https://lintian.debian.org/tags/copyright-file-contains-full-gpl-license

**Comment by a-crate** [comment]
That link points to an error about the copyright file containing the full license, not a LICENSE file the root. Regardless, couldn't debian packing be configured to exclude this file?

**Comment by kgilmer** [comment]
The future is distro agnostic.  If this ends up causing problems to have a LICENSE file we can deal with it in the debian package builder. :+1:
